# Generated by Django 5.1.1 on 2024-10-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='established_year',
        ),
    ]
