# Generated by Django 5.1.1 on 2024-10-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_meeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
