# Generated by Django 5.1.1 on 2024-10-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_college_image_url'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='added_colleges',
            field=models.ManyToManyField(blank=True, to='college.college'),
        ),
    ]
