# Generated by Django 5.1.1 on 2024-10-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_collegetour'),
        ('student', '0002_enquiry'),
    ]

    operations = [
    ]
