# Generated by Django 5.1.1 on 2024-10-05 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_merge_0002_collegetour_0002_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abc_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('annual_income', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('category_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('disability', models.CharField(blank=True, max_length=255)),
                ('disability_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_roll_number', models.CharField(max_length=255)),
                ('exam_marks', models.IntegerField()),
                ('exam_certificate', models.FileField(blank=True, null=True, upload_to='exam_certificates/')),
                ('annual_income_certificate', models.FileField(blank=True, null=True, upload_to='income_certificates/')),
                ('additional_info', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
