# Generated by Django 5.1.1 on 2024-10-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentprofile_abc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
